# Generated by Django 2.2 on 2020-07-01 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('RUT_C', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=30)),
                ('Calle', models.CharField(max_length=30)),
                ('Numero', models.IntegerField()),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Descuento', models.IntegerField()),
                ('RUT_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('RUT_P', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Telefono', models.CharField(max_length=30)),
                ('Web', models.CharField(max_length=30)),
                ('Calle', models.CharField(max_length=30)),
                ('Numero', models.IntegerField()),
                ('Ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Ciudad')),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Comuna')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='RUT_P',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Categoria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='Comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Comuna'),
        ),
    ]
