# Generated by Django 2.2 on 2020-07-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20200702_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='Descuento',
            field=models.BooleanField(),
        ),
    ]
